name: Deploy STAGING DOM IVR 2
on:
  pull_request:
    types: [closed]
    branches: [ staging ]
jobs:
  deploy:
    name: Staging Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: ismalizarraga4/Houses
    run: echo "hola mundo"
    env:
      STAGE: 'staging'
    